# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Bio
#     url: /
#     weight: 10
#   - name: News
#     url: /#news
#     weight: 13
#   - name: Experience
#     url: experience/
#     weight: 20
#   - name: Projects
#     url: projects/
#     weight: 30
#   - name: Courses
#     url: courses/
#     weight: 40


main:
  - name: Bio
    url: /
    weight: 10
    identifier: bio
  - name: Contact
    url: /#contact
    weight: 11
    parent: bio
  - name: Current Study
    url: /#current-study
    weight: 12
    parent: bio
  - name: Career Goal
    url: /#career-goal
    weight: 13
    parent: bio
  - name: Project Highlights
    url: /#project-highlights
    weight: 14
    parent: bio
  - name: Recent Interest
    url: /#interest
    weight: 15
    parent: bio
  # - name: News
  #   url: /#news
  #   weight: 30
  #   identifier: news

  - name: Experience
    url: /experience
    weight: 40
    identifier: experience
  - name: Work
    url: /experience/#work
    weight: 41
    parent: experience
  - name: Education
    url: /experience/#Work
    weight: 42
    parent: experience
  - name: Skills & Hobbies
    url: /experience/#skills
    parent: experience
    weight: 43
  - name: Awards
    url: /experience/#awards
    parent: experience
    weight: 44
  - name: Languages
    url: /experience/#languages
    parent: experience
    weight: 45


  - name: Projects
    url: /project/
    weight: 50
    identifier: project

  - name: Blog
    url: /blog/
    weight: 51
    identifier: blog

  - name: Course
    url: course/
    weight: 60
    identifier: course
