# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Bio
#     url: /
#     weight: 10
#   - name: News
#     url: /#news
#     weight: 13
#   - name: Experience
#     url: experience/
#     weight: 20
#   - name: Projects
#     url: projects/
#     weight: 30
#   - name: Courses
#     url: courses/
#     weight: 40


main:
  - name: Bio
    url: /
    weight: 10
    identifier: bio
  - name: News
    url: /#news
    weight: 30
    identifier: news

  - name: Experience
    url: /experience/
    weight: 40
    identifier: experience
  - name: Skills & Hobbies
    url: /experience/#skills
    parent: experience
    weight: 41
  - name: Awards
    url: /experience/#awards
    parent: experience
    weight: 42
  - name: Languages
    url: /experience/#languages
    parent: experience
    weight: 43


  - name: Projects
    url: /project/
    weight: 50
    identifier: projects
  - name: Class
    url: /project/#class
    parent: projects
    weight: 51
  - name: Contest
    url: /project/#contest
    parent: projects
    weight: 52

  - name: Courses
    url: /course/
    weight: 60
    identifier: courses
  - name: In Progress
    url: /course/#current
    parent: courses
    weight: 61
  - name: Completed
    url: /course/#completed
    parent: courses
    weight: 62
