# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Jeonbuk National University - Leejinsun'
    org_name: ''
    description: '전북대학교 컴퓨터공학부 포트폴리오 · AI/모바일/웹 프로젝트'
    twitter: 'nadajinny'
    keyword: 
      - 전북대학교
      - 전북대
      - 이진선
      - 컴퓨터공학부
      - 포트폴리오
      - AI
      - 모바일
      - 웹
      - 프로젝트
    image: 'sharing.jpg'  # ✅ 이 부분을 filename 대신 image로 지정해야 함
  analytics:
    google_analytics: ''
  verification:
    google: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    show_logo: true
    logo:
      text: '이진선 포트폴리오'
      filename: 'logo.png'   # ✅ HugoBlox는 여기 filename 키를 찾음
      link: '/'

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

icon: 
  pack: 'fas'
  provider: 'fontawesome'

#기본 테마 색상
theme:
  base_color: "#B7C3F2"
  primary_color: "#D5B8F2"
  secondary_color: "#E5D1FA"

# OG 이미지 (SNS 공유용)
og_image: 'sharing.jpg'
